-- AlterTable
ALTER TABLE "SubSection" ADD COLUMN     "minPoints1" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minPoints2" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minPoints3" INTEGER NOT NULL DEFAULT 0;
